### PR TITLE
Upgrade to .NET 4.8 and Fix TLS issue

### PR DESCRIPTION
**Pull request by Tarun-Arora**
Since .NET 4.0 is no longer supported, it would be better if we upgrade to higher version.

Also please include CCExtractor.exe.config in the release and the following script for running tester on linux:

```
#!/bin/bash
exec mono CCExtractorTester.exe "$@"
```

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
You can add those files and modify the workflow yourself as well :)

**Comment by canihavesomecoffee** [comment]
Can you add that stub script as a file and include it in the release workflow? I guess that makes more sense than adding it to the readme?

**Comment by Tarun-Arora** [comment]
> Can you add that stub script as a file and include it in the release workflow? I guess that makes more sense than adding it to the readme?

Moving the script as a file was okay, but should a static script be included in the release? Like it would not be useful for windows users also...

**Comment by Tarun-Arora** [comment]
@thealphadollar This PR has been raised corresponding to the issue faced during https://github.com/CCExtractor/sample-platform/pull/702.

**Pull request merged**
